version: '2'
services:
    web:
        build: . 
#        image: sivertigo/webapp
        command: ["rails","server","-p","3000","-b","0.0.0.0"]
        volumes:
                      - ./myworkdir:/myworkdir
        ports:
            - "3000:3000"
